In [1]:
import numpy as np

def create_custom_identity(size, value, index):
    # Create an identity matrix of the given size
    identity_matrix = np.eye(size)
    
    # Insert the specified value at the given index
    identity_matrix[index] = value
    
    return identity_matrix

# Example usage:
# Create a 4x4 identity matrix with 10 at index (1, 2)
custom_identity = create_custom_identity(4, 10, (1, 2))
print(custom_identity)

[[ 1.  0.  0.  0.]
 [ 0.  1. 10.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
